# Use the official Kong image from Docker Hub
FROM kong:latest

# Set environment variables for Kong
ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/kong.yaml
ENV KONG_PROXY_ACCESS_LOG=/dev/stdout
ENV KONG_ADMIN_ACCESS_LOG=/dev/stdout
ENV KONG_PROXY_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_LISTEN=0.0.0.0:8001

# Create a directory for Kong configuration
RUN mkdir -p /etc/kong

# Optionally, copy your Kong configuration file into the container
COPY kong.yaml ./

VOLUME [ "/kong" ]

# Expose ports
EXPOSE 8000 8443 8001 8002

# Start Kong
CMD ["kong", "docker-start"]