version: '3.8'

services:
  fitnessclass:
    build: ./fitness_classes
    ports:
      - "5500:5500"
    environment:
      # - dbURL=mysql+mysqlconnector://is213@host.docker.internal:8889/fitnessclass
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/fitnessclass
    networks:
      - my_network

  viewclasses:
    build: ./view_classes
    ports:
      - "5200:5200"
    networks:
      - my_network

  userbooking:
    build: ./user_bookings
    ports:
      - "5010:5010"
    environment:
      # - dbURL=mysql+mysqlconnector://is213@host.docker.internal:8889/userbooking
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/userbooking
    networks:
      - my_network

  rating:
    build: ./ratings
    ports:
      - "5004:5004"
    environment:
      # - dbURL=mysql+mysqlconnector://is213@host.docker.internal:8889/classRatings
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/classRatings
    networks:
      - my_network

  getbooking:
    build: ./GetBooking
    ports:
      - "5101:5101"
    networks:
      - my_network

  stripe:
    build: ./stripe
    ports:
      - "4242:4242"
    networks:
      - my_network

  cancelbooking:
    build: ./cancel_booking
    ports:
      - "5105:5105"
    networks:
      - my_network

  makereview:
    build: ./MakeReview
    ports:
      - "5003:5003"
    networks:
      - my_network

  makebooking:
    build: ./MakeBooking
    ports:
      - "5100:5100"
    networks:
      - my_network
  
  map:
    build: ./Map
    ports:
      - "5110:80"
    networks:
      - my_network

  email:   
    build: ./activity_log/activity-log
    ports:
      - "8080:8080"
    networks:
     - my_network

networks:
  my_network:
    driver: bridge

